### ISSUE TITLE
Probably wrong links on the main website

### ISSUE THREAD

**Issue by aleksmelnikov** [cenotelie/hime#67]
![hime_wrong_links](https://user-images.githubusercontent.com/22053918/79747486-6b3d8580-8314-11ea-8814-906101a8f22c.jpg)
Links v3.3.2 and v3.4.0 reference to v3.3.1

**Comment by woutersl** [comment]
Yes the links are a bit misleading. In fact, if the API did not change at all we do not re-upload a full version of the documentation. This happens when a new version only contains bugfixes that have no impact on the API. It appears this was the case for the versions you mentioned.
I guess we could always upload the documentation regardless of the fact it did not change.

**Comment by aleksmelnikov** [comment]
@woutersl , thank you for explain. I close this issue.
